package com.glwebserv.admin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-28T13:57:31.480+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://Admin.GLWebServ.com", name = "AdminWebServ")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminWebServ {

    @Action(input = "http://Admin.GLWebServ.com/AdminWebServ/runRequest", output = "http://Admin.GLWebServ.com/AdminWebServ/runResponse")
    @RequestWrapper(localName = "run", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.Run")
    @WebMethod
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.RunResponse")
    public void run();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://Admin.GLWebServ.com/AdminWebServ/getPartnersRequest", output = "http://Admin.GLWebServ.com/AdminWebServ/getPartnersResponse")
    @RequestWrapper(localName = "getPartners", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.GetPartners")
    @WebMethod
    @ResponseWrapper(localName = "getPartnersResponse", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.GetPartnersResponse")
    public java.lang.String getPartners(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://Admin.GLWebServ.com/AdminWebServ/CreatePartnerRequest", output = "http://Admin.GLWebServ.com/AdminWebServ/CreatePartnerResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://Admin.GLWebServ.com/AdminWebServ/CreatePartner/Fault/Exception")})
    @RequestWrapper(localName = "CreatePartner", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.CreatePartner")
    @WebMethod(operationName = "CreatePartner")
    @ResponseWrapper(localName = "CreatePartnerResponse", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.CreatePartnerResponse")
    public boolean createPartner(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://Admin.GLWebServ.com/AdminWebServ/ConnectRequest", output = "http://Admin.GLWebServ.com/AdminWebServ/ConnectResponse", fault = {@FaultAction(className = NoSuchAlgorithmException_Exception.class, value = "http://Admin.GLWebServ.com/AdminWebServ/Connect/Fault/NoSuchAlgorithmException")})
    @RequestWrapper(localName = "Connect", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.Connect")
    @WebMethod(operationName = "Connect")
    @ResponseWrapper(localName = "ConnectResponse", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.ConnectResponse")
    public int connect(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws NoSuchAlgorithmException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://Admin.GLWebServ.com/AdminWebServ/CreatePartnerWithNameRequest", output = "http://Admin.GLWebServ.com/AdminWebServ/CreatePartnerWithNameResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://Admin.GLWebServ.com/AdminWebServ/CreatePartnerWithName/Fault/Exception")})
    @RequestWrapper(localName = "CreatePartnerWithName", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.CreatePartnerWithName")
    @WebMethod(operationName = "CreatePartnerWithName")
    @ResponseWrapper(localName = "CreatePartnerWithNameResponse", targetNamespace = "http://Admin.GLWebServ.com", className = "com.glwebserv.admin.CreatePartnerWithNameResponse")
    public boolean createPartnerWithName(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws Exception_Exception;
}
