
package com.glwebserv.admin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-28T13:57:31.448+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "Exception", targetNamespace = "http://Admin.GLWebServ.com")
public class Exception_Exception extends java.lang.Exception {
    
    private com.glwebserv.admin.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.glwebserv.admin.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.glwebserv.admin.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.glwebserv.admin.Exception getFaultInfo() {
        return this.exception;
    }
}
