
package com.glwebserv.connexion;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-28T00:51:46.297+01:00
 * Generated source version: 2.7.7
 * 
 */
public final class ConnexionWebServ_ConnexionWebServPort_Client {

    private static final QName SERVICE_NAME = new QName("http://Connexion.GLWebServ.com", "ConnexionService");

    private ConnexionWebServ_ConnexionWebServPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConnexionService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConnexionService ss = new ConnexionService(wsdlURL, SERVICE_NAME);
        ConnexionWebServ port = ss.getConnexionWebServPort();  
        
        {
        System.out.println("Invoking getAdmin...");
        com.glwebserv.connexion.Administrator _getAdmin__return = port.getAdmin();
        System.out.println("getAdmin.result=" + _getAdmin__return);


        }
        {
        System.out.println("Invoking sendMessages...");
        java.lang.String _sendMessages_arg0 = "";
        try {
            port.sendMessages(_sendMessages_arg0);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking newRunner...");
        java.lang.String _newRunner_arg0 = "";
        java.lang.String _newRunner_arg1 = "";
        boolean _newRunner__return = port.newRunner(_newRunner_arg0, _newRunner_arg1);
        System.out.println("newRunner.result=" + _newRunner__return);


        }

        System.exit(0);
    }

}
