package com.glwebserv.connexion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-28T00:51:46.527+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "ConnexionService", 
                  wsdlLocation = "http://localhost:8090/connexion?wsdl",
                  targetNamespace = "http://Connexion.GLWebServ.com") 
public class ConnexionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Connexion.GLWebServ.com", "ConnexionService");
    public final static QName ConnexionWebServPort = new QName("http://Connexion.GLWebServ.com", "ConnexionWebServPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/connexion?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConnexionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/connexion?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConnexionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConnexionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConnexionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConnexionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConnexionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConnexionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConnexionWebServ
     */
    @WebEndpoint(name = "ConnexionWebServPort")
    public ConnexionWebServ getConnexionWebServPort() {
        return super.getPort(ConnexionWebServPort, ConnexionWebServ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConnexionWebServ
     */
    @WebEndpoint(name = "ConnexionWebServPort")
    public ConnexionWebServ getConnexionWebServPort(WebServiceFeature... features) {
        return super.getPort(ConnexionWebServPort, ConnexionWebServ.class, features);
    }

}
