
package com.glwebserv.partners;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-28T13:57:28.089+01:00
 * Generated source version: 2.7.7
 * 
 */
public final class PartnersWebServ_PartnersWebServPort_Client {

    private static final QName SERVICE_NAME = new QName("http://Partners.GLWebServ.com", "PartnersService");

    private PartnersWebServ_PartnersWebServPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PartnersService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PartnersService ss = new PartnersService(wsdlURL, SERVICE_NAME);
        PartnersWebServ port = ss.getPartnersWebServPort();  
        
        {
        System.out.println("Invoking getName...");
        java.lang.String _getName_arg0 = "";
        java.lang.String _getName__return = port.getName(_getName_arg0);
        System.out.println("getName.result=" + _getName__return);


        }
        {
        System.out.println("Invoking getPartnersList...");
        java.lang.String _getPartnersList__return = port.getPartnersList();
        System.out.println("getPartnersList.result=" + _getPartnersList__return);


        }
        {
        System.out.println("Invoking getPicture...");
        java.lang.String _getPicture_arg0 = "";
        java.lang.String _getPicture__return = port.getPicture(_getPicture_arg0);
        System.out.println("getPicture.result=" + _getPicture__return);


        }

        System.exit(0);
    }

}
