package com.glwebserv.partners;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-28T13:57:28.275+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://Partners.GLWebServ.com", name = "PartnersWebServ")
@XmlSeeAlso({ObjectFactory.class})
public interface PartnersWebServ {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://Partners.GLWebServ.com/PartnersWebServ/getNameRequest", output = "http://Partners.GLWebServ.com/PartnersWebServ/getNameResponse")
    @RequestWrapper(localName = "getName", targetNamespace = "http://Partners.GLWebServ.com", className = "com.glwebserv.partners.GetName")
    @WebMethod
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://Partners.GLWebServ.com", className = "com.glwebserv.partners.GetNameResponse")
    public java.lang.String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://Partners.GLWebServ.com/PartnersWebServ/getPartnersListRequest", output = "http://Partners.GLWebServ.com/PartnersWebServ/getPartnersListResponse")
    @RequestWrapper(localName = "getPartnersList", targetNamespace = "http://Partners.GLWebServ.com", className = "com.glwebserv.partners.GetPartnersList")
    @WebMethod
    @ResponseWrapper(localName = "getPartnersListResponse", targetNamespace = "http://Partners.GLWebServ.com", className = "com.glwebserv.partners.GetPartnersListResponse")
    public java.lang.String getPartnersList();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://Partners.GLWebServ.com/PartnersWebServ/getPictureRequest", output = "http://Partners.GLWebServ.com/PartnersWebServ/getPictureResponse")
    @RequestWrapper(localName = "getPicture", targetNamespace = "http://Partners.GLWebServ.com", className = "com.glwebserv.partners.GetPicture")
    @WebMethod
    @ResponseWrapper(localName = "getPictureResponse", targetNamespace = "http://Partners.GLWebServ.com", className = "com.glwebserv.partners.GetPictureResponse")
    public java.lang.String getPicture(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
